### ISSUE TITLE
seg_models.models.pspnet error ?

### ISSUE THREAD

**Issue by yghcats** [twke18/Adaptive_Affinity_Fields#12]
Hi,I run: python pyscripts/inference/inference.py 
The following error message appears:
Traceback (most recent call last):
  File "pyscripts/inference/inference.py", line 14, in <module>
    from seg_models.models.pspnet import pspnet_resnet101 as model
ImportError: No module named seg_models.models.pspnet

What is the problem, please?
thanks!

**Comment by jyhjinghwang** [comment]
Please download the Imagenet pre-trained model first as stated in README.

**Comment by jyhjinghwang** [comment]
Please check your environment so that Python path includes the root of this directory.

**Comment by yghcats** [comment]
@jyhjinghwang thanks!
