### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by zhly0** [twke18/Adaptive_Affinity_Fields#2]
The inference code could not run!can you give some default input parameter,so that I could just set the input output data directory and list!Thank you.

**Comment by twke18** [comment]
Please take a look at [our bashscripts examples](https://github.com/twke18/Adaptive_Affinity_Fields/tree/master/bashscripts) for the input arguments. For example, [these lines](https://github.com/twke18/Adaptive_Affinity_Fields/blob/ac2cfb50e93f509fd08f461aea4cab651f3db626/bashscripts/voc12/train_pspnet.sh#L65-L77) are for single-input inference, and [these lines](https://github.com/twke18/Adaptive_Affinity_Fields/blob/ac2cfb50e93f509fd08f461aea4cab651f3db626/bashscripts/voc12/train_pspnet.sh#L109-L123) are for inference with multi-scale inputs and left-right flipping on Pascal VOC 2012.

**Comment by zhly0** [comment]
Thanks!

**Comment by Jee-King** [comment]
Hi, 
How to make the inference.py run. What model is needed besides _resnet_v1_101.ckpt_?
Thank you very much!
