### ISSUE TITLE
The question about dataset

### ISSUE THREAD

**Issue by shenggedeqiang** [twke18/Adaptive_Affinity_Fields#7]
Hi，should I change the folder from VOCdevkit/VOC2012/SegmentationClass to VOCdevkit/VOC2012/segcls? Because there is no segcls folder in the dataset VOC2012.

**Comment by twke18** [comment]
Yes, VOCdevkit/VOC2012/segcls should be exactly same as VOCdevkit/VOC2012/SegmentationClass.

**Comment by shenggedeqiang** [comment]
> Yes, VOCdevkit/VOC2012/segcls should be exactly same as VOCdevkit/VOC2012/SegmentationClass.

**Comment by shenggedeqiang** [comment]
> Yes, VOCdevkit/VOC2012/segcls should be exactly same as VOCdevkit/VOC2012/SegmentationClass.

Thank you for your reply.I am running the train_pspnet.sh,but I got some errors:
1、W tensorflow/core/framework/op_kernel.cc:1192] Not found: VOCdevkit/sbd/dataset/clsimg/2009_001501.png; No such file or directory
2、Unsuccessful TensorSliceReader constructor: Failed to find any matching files for snapshots/voc12/pspnet/p336_bs8_lr1e-3_it30k/stage1/model.ckpt-30000
3、Unsuccessful TensorSliceReader constructor: Failed to find any matching files for snapshots/voc12/pspnet/p336_bs8_lr1e-3_it30k/stage2/model.ckpt-30000

It seems that there are something wrong with the loader or saver because them did't get the right model.ckpt-30000 in stage1 and stage2.
How can I slove these problems?
