### ISSUE TITLE
How to calculate boundary recall?

### ISSUE THREAD

**Issue by XiaLiPKU** [twke18/Adaptive_Affinity_Fields#8]
In your paper, the detail for calculating BR is not offered. Also, in your code, I can't find any cue.
You only offer a citation to Contour Detection and Hierarchical Image Segmentation.
But in this paper, the authors refered a way to output the precision-recall curve, instead of a concrete value. So, I just wonder, how to calculate this

**Comment by jyhjinghwang** [comment]
1. Please find the evaluation code on BSDS500 dataset website here:
https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/resources.html
We did not include this evaluation in the repo as we did not reimplement it but reused their package.

2. The usual contour evaluation will produce a precision-recall curve as they calculate precision and recall given 100 different thresholds from 0 to 1. However, in semantic segmentation, we don't have or need the intensity of contours. Therefore, there is only one number for precision or recall.
