### ISSUE TITLE
Time overhead

### ISSUE THREAD

**Issue by arc144** [twke18/Adaptive_Affinity_Fields#9]
Hi, I've adapted the code here for Pytorch and it seems to have worked ok. However I'm experience a huge overhead in terms of time. Without AAF a single epoch would take ~18min, now it's taking around 29min. Is an overhead of this magnitude to be expected?
Thanks
Kind regards,

**Comment by twke18** [comment]
Hi, we expect the computational overhead to be around 10~20% in Tensorflow.
